#!/usr/bin/perl -w

# Sample Facebook code.
# Copyright 2009 Paul Fenwick
# You may modify and redistribute this code under the same terms
# as Perl 5.10 itself.

use strict;
use warnings;
use autodie;
use WWW::Facebook::API;
use Data::Dumper;
use Config::Tiny;

use constant CONFIG_FILE => "/home/jesse/paulbook.ini";

# At the very least, we need an api_key and secret in our config.

my $config = Config::Tiny->read(CONFIG_FILE);

my $connect_config = $config->{connection};

my $fb = WWW::Facebook::API->new(
    desktop => 1,

    throw_errors => 1,
    debug => 0,

    %$connect_config,
);

# Nasty session setup code.

if ( not $connect_config->{session_key} ) {

    if (not $ARGV[0]) {
        print "Login needed...  Go to...\n";
        print $fb->get_infinite_session_url,"\n";
        print "Then run again with your one-time code as a command-line argument\n";

        exit 0;

    } else {
        # Ah! We have a token...

        my $token = $ARGV[0];

        $fb->auth->get_session($token);

        # Now save all the details we got from that login.

        $connect_config->{secret}          = $fb->secret;
        $connect_config->{session_expires} = $fb->session_expires;
        $connect_config->{session_key}     = $fb->session_key;
        $connect_config->{session_uid}     = $fb->session_uid;

        $config->write(CONFIG_FILE);

        print "Login complete.  Please run application again.\n";

        exit 0;

    }
}

my $app_user = $fb->users->get_logged_in_user;
my %perms_result = %{($fb->fql->query( query => qq{SELECT read_stream,publish_stream FROM permissions WHERE uid=}.$app_user))->[0]};
unless ($perms_result{publish_stream} && $perms_result{read_stream}) {
	print "Next up, you need to give this app permissions to see your stream. Visit the url below and the rerun the application\n";
print $fb->get_url('custom', 'http://www.facebook.com/connect/prompt_permissions.php',
	next=>'http://www.facebook.com/connect/login_success.html?xxRESULTTOKENxx',
	display=> 'popup',
	ext_perm=> 'read_stream,publish_stream');
	exit 0;
}

# Awesome data mining of friends code!

warn "OK";
my $city = $ARGV[0] // "Sydney";

my $result = $fb->stream->get( metadata => [qw(albums profiles photo_tags)]);

#my $result = $fb->fql->query(query => qq{ SELECT name, sex, current_location.city FROM user WHERE 1 });
	#WHERE uid IN (SELECT uid2 FROM friend WHERE uid1 = $app_user) AND "$city" IN current_location

print Dumper $result;
